-- 집계함수에서 case 활용
-- [1] 주문년월별 계좌이체(PAY_TP=BANK) 건수와 카드결제(PAY_TP=CARD) 건수

SELECT TO_CHAR(T1.ORD_DT, 'YYYYMM') ORD_YM
       , SUM(CASE WHEN T1.PAY_TP = 'BANK' THEN 1 END) BANK_PAY_CNT -- ELSE를 선언하지 않았기 때문에 BANK가 아닌 경우는 자동으로 NULL 처리 연산되지 않음.
       , SUM(CASE WHEN T1.PAY_TP = 'CARD' THEN 1 END) CARD_PAY_CNT
  FROM T_ORD T1
 WHERE T1.ORD_ST = 'COMP'
 GROUP BY TO_CHAR(T1.ORD_DT, 'YYYYMM')
 ORDER BY TO_CHAR(T1.ORD_DT, 'YYYYMM');
 
-- 분석용 데이터를 보여주기 위해 자주 사용하는 기법이다.

-- [2] 지불유형(PAY_TP)별 주문건수(주문 건수를 주문년월별로 컬럼으로 표시)

SELECT T1.PAY_TP
       , COUNT(CASE WHEN TO_CHAR(T1.ORD_DT, 'YYYYMM') = '201701' THEN 'X' END) ORD_CNT_1701
       , COUNT(CASE WHEN TO_CHAR(T1.ORD_DT, 'YYYYMM') = '201702' THEN 'X' END) ORD_CNT_1702
       , COUNT(CASE WHEN TO_CHAR(T1.ORD_DT, 'YYYYMM') = '201703' THEN 'X' END) ORD_CNT_1703
       , COUNT(CASE WHEN TO_CHAR(T1.ORD_DT, 'YYYYMM') = '201704' THEN 'X' END) ORD_CNT_1704
       , COUNT(CASE WHEN TO_CHAR(T1.ORD_DT, 'YYYYMM') = '201705' THEN 'X' END) ORD_CNT_1705
       , COUNT(CASE WHEN TO_CHAR(T1.ORD_DT, 'YYYYMM') = '201706' THEN 'X' END) ORD_CNT_1706
       , COUNT(CASE WHEN TO_CHAR(T1.ORD_DT, 'YYYYMM') = '201707' THEN 'X' END) ORD_CNT_1707
       , COUNT(CASE WHEN TO_CHAR(T1.ORD_DT, 'YYYYMM') = '201708' THEN 'X' END) ORD_CNT_1708
       , COUNT(CASE WHEN TO_CHAR(T1.ORD_DT, 'YYYYMM') = '201709' THEN 'X' END) ORD_CNT_1709
       , COUNT(CASE WHEN TO_CHAR(T1.ORD_DT, 'YYYYMM') = '201710' THEN 'X' END) ORD_CNT_1710
       , COUNT(CASE WHEN TO_CHAR(T1.ORD_DT, 'YYYYMM') = '201711' THEN 'X' END) ORD_CNT_1711
       , COUNT(CASE WHEN TO_CHAR(T1.ORD_DT, 'YYYYMM') = '201712' THEN 'X' END) ORD_CNT_1712
  FROM T_ORD T1
 WHERE T1.ORD_ST = 'COMP'
 GROUP BY T1.PAY_TP
 ORDER BY T1.PAY_TP;
 
 SELECT  T1.CUS_ID, T1.CUS_GD, T2.ORD_SEQ, T2.CUS_ID, T2.ORD_DT
FROM    M_CUS T1
        ,T_ORD T2
WHERE   T1.CUS_ID = T2.CUS_ID
AND     T1.CUS_GD = 'A'
AND     T2.ORD_DT >= TO_DATE('20170101','YYYYMMDD')
AND     T2.ORD_DT <  TO_DATE('20170201','YYYYMMDD');

SELECT  T1.CUS_ID, T1.CUS_NM
        ,COUNT(DISTINCT T2.ITM_ID||'-'||TO_CHAR(T2.EVL_LST_NO)) EVAL_CNT
        ,COUNT(DISTINCT T3.ORD_SEQ) ORD_CNT
FROM    M_CUS T1
        ,T_ITM_EVL T2
        ,T_ORD T3
WHERE   T1.CUS_ID = T2.CUS_ID
AND     T1.CUS_ID = T3.CUS_ID
AND     T1.CUS_ID = 'CUS_0023'
AND     T2.EVL_DT >= TO_DATE('20170301','YYYYMMDD')
AND     T2.EVL_DT <  TO_DATE('20170401','YYYYMMDD')
AND     T3.ORD_DT >= TO_DATE('20170301','YYYYMMDD')
AND     T3.ORD_DT <  TO_DATE('20170401','YYYYMMDD')
GROUP BY T1.CUS_ID, T1.CUS_NM;

SELECT T1.CUS_ID, MAX(T1.CUS_NM) CUS_NM, SUM(T1.EVL_CNT) EVL_CNT, SUM(T1.ORD_CNT) ORD_CNT
  FROM (
        SELECT  T1.CUS_ID, MAX(T1.CUS_NM) CUS_NM, COUNT(*) EVL_CNT, NULL ORD_CNT
        FROM    M_CUS T1
                , T_ITM_EVL T2
        WHERE   T1.CUS_ID = T2.CUS_ID
        AND     T2.CUS_ID = 'CUS_0023'
        AND     T2.EVL_DT >= TO_DATE('20170301','YYYYMMDD')
        AND     T2.EVL_DT <  TO_DATE('20170401','YYYYMMDD')
        GROUP BY T1.CUS_ID, T1.CUS_NM
        UNION ALL
        SELECT T1.CUS_ID, MAX(T1.CUS_NM) CUS_NM, NULL EVL_CNT, COUNT(*) ORD_CNT
        FROM    M_CUS T1
                , T_ORD T3
        WHERE   T1.CUS_ID = T3.CUS_ID
        AND     T3.CUS_ID = 'CUS_0023'
        AND     T3.ORD_DT >= TO_DATE('20170301','YYYYMMDD')
        AND     T3.ORD_DT <  TO_DATE('20170401','YYYYMMDD')
        GROUP BY T1.CUS_ID, T1.CUS_NM
        ) T1
  GROUP BY T1.CUS_ID;
  
SELECT T1.CUS_ID, MAX(T1.CUS_NM) CUS_NM, SUM(T4.EVL_CNT) EVL_CNT, SUM(T4.ORD_CNT) ORD_CNT
  FROM M_CUS T1
        ,(
        SELECT  T2.CUS_ID, COUNT(*) EVL_CNT, NULL ORD_CNT
        FROM    T_ITM_EVL T2
        WHERE   T2.CUS_ID = 'CUS_0023'
        AND     T2.EVL_DT >= TO_DATE('20170301','YYYYMMDD')
        AND     T2.EVL_DT <  TO_DATE('20170401','YYYYMMDD')
        GROUP BY T2.CUS_ID
        UNION ALL
        SELECT  T3.CUS_ID, NULL EVL_CNT, COUNT(*) ORD_CNT
        FROM    T_ORD T3
        WHERE   T3.CUS_ID = 'CUS_0023'
        AND     T3.ORD_DT >= TO_DATE('20170301','YYYYMMDD')
        AND     T3.ORD_DT <  TO_DATE('20170401','YYYYMMDD')
        GROUP BY T3.CUS_ID
        ) T4
  WHERE T1.CUS_ID = T4.CUS_ID
  GROUP BY T1.CUS_ID;